# Generated by Django 4.0.6 on 2022-07-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockprice',
            unique_together={('token_pair', 'block_number')},
        ),
        migrations.CreateModel(
            name='BlockPriceUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_block_number', models.IntegerField(default=-1, verbose_name='Min Block Number')),
                ('max_block_number', models.IntegerField(default=-1, verbose_name='Max Block Number')),
                ('token_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.tokenpair', unique=True)),
            ],
        ),
    ]
