# Generated by Django 4.0.6 on 2022-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0002_alter_blockprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpriceupdaterecord',
            name='min_block_number',
            field=models.IntegerField(default=10000000000000, verbose_name='Min Block Number'),
        ),
    ]
