# Generated by Django 4.0.6 on 2022-08-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0003_alter_blockpriceupdaterecord_min_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpriceupdaterecord',
            name='data_amount',
            field=models.IntegerField(default=-1, verbose_name='Data Amount'),
        ),
        migrations.AlterField(
            model_name='blockpriceupdaterecord',
            name='min_block_number',
            field=models.IntegerField(default=2147483647, verbose_name='Min Block Number'),
        ),
    ]
