# Generated by Django 4.0.6 on 2022-08-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0004_blockpriceupdaterecord_data_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockpriceupdaterecord',
            name='data_amount',
        ),
    ]
