# Generated by Django 4.0.6 on 2022-08-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0005_remove_blockpriceupdaterecord_data_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatencyRecordPer6424',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.FloatField(default=-1)),
                ('data_crawled_at', models.DateTimeField(auto_now=True)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.blocknumber')),
                ('token_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.tokenpair')),
            ],
            options={
                'unique_together': {('token_pair', 'block_number')},
            },
        ),
    ]
