# Generated by Django 4.0.6 on 2022-08-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0007_frequency_latencupdaterecord_latencyrecord_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='latencupdaterecord',
            unique_together={('token_pair', 'frequency')},
        ),
    ]
