# Generated by Django 4.0.6 on 2022-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0008_alter_latencupdaterecord_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='frequency',
        ),
        migrations.AddField(
            model_name='frequency',
            name='frequency_num',
            field=models.IntegerField(default=-1, verbose_name='Frequency_num'),
        ),
    ]
