# Generated by Django 4.0.6 on 2022-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0009_remove_frequency_frequency_frequency_frequency_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='frequency_num',
            field=models.IntegerField(default=-1, unique=True, verbose_name='Frequency_num'),
        ),
    ]
