# Generated by Django 4.0.6 on 2022-08-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0010_alter_frequency_frequency_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='latencyrecord',
            unique_together={('block_number', 'frequency')},
        ),
        migrations.RemoveField(
            model_name='latencyrecord',
            name='token_pair',
        ),
    ]
