# Generated by Django 4.0.6 on 2022-08-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0011_alter_latencyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpriceupdaterecord',
            name='token_pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastorage.tokenpair'),
        ),
        migrations.AlterField(
            model_name='latencupdaterecord',
            name='token_pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastorage.tokenpair'),
        ),
        migrations.DeleteModel(
            name='LatencyRecord',
        ),
    ]
