# Generated by Django 4.0.6 on 2022-08-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualization', '0013_latencyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatencUpdateRecord',
        ),
    ]
