# Generated by Django 4.0.6 on 2022-08-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('datavisualization', '0015_latencupdaterecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatencUpdateRecord',
            new_name='LatencyUpdateRecord',
        ),
    ]
