# Generated by Django 4.0.6 on 2022-08-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('token_pair', 'block_number', 'index')},
        ),
    ]
