# Generated by Django 4.0.6 on 2022-08-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastorage', '0002_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
                ('asset', models.CharField(default='', max_length=100)),
                ('liquidity_rate', models.FloatField(default=-1)),
                ('stable_borrow_rate', models.FloatField(default=-1)),
                ('variable_borrow_rate', models.FloatField(default=-1)),
                ('liquidity_index', models.FloatField(default=-1)),
                ('variable_borrow_index', models.FloatField(default=-1)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.blocknumber')),
            ],
            options={
                'unique_together': {('index', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='LendingPoolInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
                ('agent', models.CharField(default='', max_length=100)),
                ('on_behalf_of', models.CharField(default='', max_length=100)),
                ('action', models.CharField(default='', max_length=100)),
                ('asset', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=-1)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.blocknumber')),
            ],
            options={
                'unique_together': {('index', 'block_number')},
            },
        ),
    ]
