# Generated by Django 4.0.6 on 2022-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingPoolUdateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=100, unique=True)),
                ('min_block_number', models.IntegerField(default=-1, verbose_name='Min Block Number')),
                ('max_block_number', models.IntegerField(default=-1, verbose_name='Max Block Number')),
                ('data_amount', models.IntegerField(default=-1, verbose_name='Data Amount')),
            ],
        ),
    ]
