# Generated by Django 4.0.6 on 2022-08-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_summary'),
        ('debtmonitor', '0003_alter_lendingpooludatesummary_min_block_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendingpoolinteraction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lendingpoolinteraction',
            name='asset',
        ),
        migrations.AddField(
            model_name='lendingpoolinteraction',
            name='rate',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='lendingpoolinteraction',
            name='rate_mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lendingpoolinteraction',
            name='reserve',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='LiquidationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
                ('on_behalf_of', models.CharField(default='', max_length=100)),
                ('collateral_asset', models.CharField(default='', max_length=100)),
                ('debt_asset', models.CharField(default='', max_length=100)),
                ('debt_to_cover', models.FloatField(default=-1)),
                ('liquidated_collateral_amount', models.FloatField(default=-1)),
                ('liquidator', models.CharField(default='', max_length=100)),
                ('rate_mode', models.CharField(default='', max_length=100)),
                ('rate', models.FloatField(default=-1)),
                ('receive_atoken', models.BooleanField(default=False)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.blocknumber')),
            ],
            options={
                'unique_together': {('index', 'block_number')},
            },
        ),
    ]
