# Generated by Django 4.0.6 on 2022-08-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtmonitor', '0004_remove_lendingpoolinteraction_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservesstatus',
            old_name='asset',
            new_name='reserve',
        ),
    ]
