# Generated by Django 4.0.6 on 2022-08-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtmonitor', '0005_rename_asset_reservesstatus_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationcall',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='liquidationcall',
            name='rate_mode',
        ),
    ]
