# Generated by Django 4.0.6 on 2022-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtmonitor', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpoolinteraction',
            name='transaction_hash',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='liquidationcall',
            name='transaction_hash',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservesstatus',
            name='transaction_hash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
